name: Build latest main and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: theahat
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean package

      - name: Push Images to Docker Registry
        run: docker push -a theahat/isegranfasade
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: theahat
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create-manifest
        run: |
          docker manifest create theahat/isegranfasade:v0.0.0 --amend theahat/isegranfasade:v0.0.0-x86_64
          docker manifest push theahat/isegranfasade:v0.0.0
          docker manifest create theahat/isegranfasade:latest --amend theahat/isegranfasade:v0.0.0-x86_64
          docker manifest push theahat/isegranfasade:latest
