name: Build tag and deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: theahat
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build with Maven
        run: mvn clean package

      - name: Push Images to Docker Registry
        run: docker push -a theahat/isegranfasade
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: theahat
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: create-manifest
        run: |
          docker manifest create theahat/isegranfasade:${{ github.ref_name }} --amend theahat/isegranfasade:${{ github.ref_name }}-x86_64
          docker manifest push theahat/isegranfasade:${{ github.ref_name }}
          docker manifest create theahat/isegranfasade:latest --amend theahat/isegranfasade:${{ github.ref_name }}-x86_64
          docker manifest push theahat/isegranfasade:latest
